#!/bin/bash

#
# Copyright (c) 2025 Jotheeswar-devpy.
# Joe_Musicbot is an open-source Telegram music bot licensed under AGPL-3.0.
# All rights reserved where applicable.
#
#

echo "Starting Joe_Musicbot..."

python3 -m Joe_Musicbot
